# Project: thuvien
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"D:/App/DevC/Dev-Cpp/MinGW32/lib" -L"D:/App/DevC/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -g3
INCS     = -I"D:/App/DevC/Dev-Cpp/MinGW32/include" -I"D:/App/DevC/Dev-Cpp/MinGW32/mingw32/include" -I"D:/App/DevC/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"D:/App/DevC/Dev-Cpp/MinGW32/include" -I"D:/App/DevC/Dev-Cpp/MinGW32/mingw32/include" -I"D:/App/DevC/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"D:/App/DevC/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = thuvien.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
